### ISSUE TITLE
_ki_ missing in Lev 5:21. 

### ISSUE THREAD

**Issue by fhardison** [Clear-Bible/macula-hebrew#112] opened 2024-03-07 18:56 UTC
If the text is based on WLC, then there is a _ki_ missing after _nefesh_ in Lev 5:21.

**Comment by jacobwegner** [comment] 2024-03-07 23:57
@fhardison Thanks for flagging this.

We are (currently!) shipping three versions of data in this repo:

> 1) `nodes` contains this data in a set of nested Node elements suitable for many NLP systems and other systems that use recursive algorithms
> 2) `lowfat` contains the same data in a form more suitable for some kinds of query systems and some kinds of display.
> 3) `TSV` contains the word-level data in a TSV table, without syntactic tree structure. This is simpler for many programs that do not need the complexity of graph structures.

We have an open issue for fixing the `lowfat` dataset, where indeed there are some gaps in the data: 

https://github.com/Clear-Bible/macula-hebrew/issues/65

I just merged a PR last month (https://github.com/Clear-Bible/macula-hebrew/pull/110) that updated the `TSV` dataset; it is derived from the `nodes` dataset, and both `nodes` and `TSV` have all of the text from the WLC.

I apologize for any confusion this may have caused you; I will be sure to loop back when we have an updated version of the `lowfat` data that corrects the issue from #65.

Please let us know if you the `nodes` or `TSV` datasets won't cover what you're hoping to do with the data, and I'll see if there is anything else we can do to help assist.

**Comment by jacobwegner** [comment] 2024-03-07 23:57
Is a duplicate of #65

**Closed by jacobwegner** 2024-03-07 23:57 UTC
