### ISSUE TITLE
Lowfat is falling behind (missing attributes)

### ISSUE THREAD

**Issue by jonathanrobie** [Clear-Bible/macula-hebrew#52] opened 2022-06-13 16:08 UTC
The Nodes representation contains attributes that aren't in Lowfat:

- English
- Mandarin
- SDBH

Perhaps others.

```xml
<m word="GEN 1:1!1" xml:id="o010010010012" morph="Ncfsa" lang="H" lemma="7225" after=" " pos="noun" type="common" gender="feminine" number="singular" state="absolute" english="beginning" mandarin="起初" SDBH="רֵאשִׁית:002003003004:Begin:beginning">רֵאשִׁית</m>    
```

**Comment by ryderwishart** [comment] 2022-06-13 22:41
It turns out we lost some nodes on the last transformation @klosoter @jonathanrobie. For example, we lost `xml:id="o010380240022"`. Any chance we can revert the last merge before adding glosses/annotations and try again?

The problematic commit is 
> 5e3d1661 Added glosses/annotations | changed Node/@xml:id to Node/@n 

and the commit that merges it is 
> b35d3d82 Merge pull request #49 from Clear-Bible/latest-glosses-and-annotations

See diff screenshot here:
![Image](https://user-images.githubusercontent.com/19649268/173459065-bc114371-679e-4f9b-8840-9e3048483b27.png)

**Comment by klosoter** [comment] 2022-06-16 05:35
On it

**Comment by klosoter** [comment] 2022-06-16 07:28
I see what happened. Nodes 010380240022-3 (and a few others like this) got removed when I copied them to a new XML file that documents issues. I've used deepcopy now, so this should be resolved.

**Comment by klosoter** [comment] 2022-06-16 07:39
There were multiple issues with lowfat and the full trees, when I tried to add the glosses and other data there as well. Most of them are very similar to the problems I had with NT-lowfat.

In full trees:
- Changed `Node/@xml:id` to `Node/n` because it was a duplicate of `Node/m/@xml:id` (not allowed for ids)

![image](https://user-images.githubusercontent.com/61023061/174016816-052d4c29-45cc-440c-9a4d-3aed875f6f57.png)

In lowfat:
- prepended "o" to `wg/@xml:id` where absent (NCName can't start with a digit)
- there were 136 cases where `Node/m` was not changed into `wg/w`, each time with the same morph: אוּלַ֥י
    - changed `Node/m` to `wg/w`
    - applied previous operation on it to retain `Node/@nodeId` as `Node/@xml:id` (with extra "o")
    - removed `Node/@nodeId`

![image](https://user-images.githubusercontent.com/61023061/174017824-f44bdde3-027d-4587-a375-f7e9aa566419.png)

@ryderwishart, I'm interested, though, why and when did this morpheme get skipped?

**Comment by klosoter** [comment] 2022-06-16 07:40
Then I added the glosses and annotations to lowfat and full trees

**Closed** 2022-06-16 22:44 UTC
